services:
  web:
    build: ./web
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 80 --app-dir /code/web --reload
    ports:
      - "80:80"
    restart: always
    depends_on:
      - grafana
      - db
    volumes:
      - .:/code/
    # Pass test InfluxDB credentials as environmental variables in Docker container
    environment:
      - INFLUXDB_USER=labview
      - INFLUXDB_PASSWORD=labview
      - INFLUXDB_ORGANIZATION=labview
      - INFLUXDB_BUCKET=labview
      - INFLUXDB_API_TOKEN=gqswl5e1Vle8UXP6WekzyqDD54GHQpoe7qIxjkckYc62-zHIYz9jq7MB-Ci8d3MTAaynSltGHNrGdAPLBzH0LA==

  grafana:
    image: grafana/grafana:latest
    ports: 
      - "3000:3000"
    depends_on:
      - db

  db:
    image: influxdb
    ports: 
      - "8086:8086"

# TODO volumes or mounts
