version: '3.8'

services:
  web:
    build: ./web
    command: uvicorn app.main:app --reload --workers 1 --host 127.0.0.1
    ports:
      - "80:80"
    depends_on:
      - grafana
      - db

  grafana:
    image: grafana/grafana:latest
    ports: 
      - "3000:3000"
    depends_on:
      - db

  db:
    image: influxdb
    ports: 
      - "8086:8086"

# TODO volumes or mounts