version: '3.8'

services:
  web:
    build: ./web
    command: uvicorn app.main:app --reload --workers 1 --host 127.0.0.1
    ports:
      - "80:80"
    depends_on:
      - grafana
      - db
    # Pass test InfluxDB credentials as environmental variables in Docker container
    environment:
      - env 

    

  db:
    image: influxdb
    ports: 
      - "8086:8086"

  grafana:
    image: grafana/grafana
    ports: 
      - "3000:3000"
